### ISSUE TITLE
Generate KubeConfig to User With context set to their namespace(s)

### ISSUE THREAD

**Issue by mghlaiel** [creometry/dashboard#5]

**Comment by seifb01** [comment]
The generateKubeconfig rancher endpoint returns the kubeconfig based on the authorization token provided, should I then manually change it to the user and his namespace? Also, do I get the user data from the request body?

**Comment by mghlaiel** [comment]
You can get the username/email from the idp Then, you can determine the user's accessible namespaces from "rolebindings" and filters

1- get username/email

2- Find which roles/clusterrole the subject is bound to in the rolebinding/clusterrolebinding with custom filters

Example kubectl command:
kubectl get rolebindings,clusterrolebindings \ --all-namespaces \ -o custom-columns=''

3 - Once you have the role/clusterrole name, you can find out which namespaces the user is authorized to access

This is how it's done using k8s APIs exclusively

It would be easier to read about [authentication in kubernetes](https://kubernetes.io/docs/reference/access-authn-authz/authentication/) first. The relevant authentication strategies are OIDC connector (ID tokens/jwt) and bearer tokens.

> > Then understand [RBAC (authorizations)](https://kubernetes.io/docs/reference/access-authn-authz/authorization/). Relevant attribute for this matter are _user_, _group_ and _namespace_.

There are packages than do this as well. Try [this CLI](https://github.com/FairwindsOps/rbac-lookup) to get a clearer idea on what the packages do)

A similar question has been answered in [this thread ](https://github.com/kubernetes/kubernetes/issues/53248)


I will look into Rancher's API to see if there's a way to do this
