### ISSUE TITLE
Turn the provisioner into a user "account"

### ISSUE THREAD

**Issue by mghlaiel** [creometry/dashboard#54]

**Comment by seifb01** [comment]
Can you add more information to this issue?

**Comment by mghlaiel** [comment]
We will discuss it in details during the next meet. But here's a brief rational:
- User registrations now add a user to keycloack instead of creating a Rancher user
- once user created, they can be added to a project or create a new project.

In the case of an existing user:
- user login and a list of project is displayed per region (rancher instance)
- they can add a new namespace and point a repo to it
- they can also create a new project
- They can view bills and usage (other people on the team will do this)
